Simplecalculator : Add.o Sub.o Main.c
		gcc -o Simplecalculator Add.o Sub.o Main.c

Add.0 : Add.c
		gcc -c Add.c

Sub.0 : Sub.c
		gcc -c Sub.c

Main.0 : Main.c
		gcc -c Main.c

clean :
		rm *.o Simplecalculator
